# -*- coding: utf-8 -*-
"""
export_dashboard.py — 生成数据大屏(dashboard.html)所需数据 dashboard_data.js:
  1. 研究区 5 年逐月降雨(precip tif 提取, 单位 mm)
  2. 5 个重现期场景(scenarios.json)
  3. 水深分布直方图 + 预警等级统计(flood_depth_100y.tif)
"""
import os, json
import numpy as np
import rasterio
from rasterio.windows import from_bounds

os.environ["PROJ_LIB"] = r"D:\Lib\site-packages\rasterio\proj_data"
os.environ["PROJ_DATA"] = r"D:\Lib\site-packages\rasterio\proj_data"

ROOT = r"D:\Competiton"
STUDY = (113.30, 23.09, 113.34, 23.13)   # west, south, east, north
YEARS = [2021, 2022, 2023, 2024, 2025]
MONTHS = list(range(1, 13))


def study_monthly_rain():
    """返回 {year: [12 个月雨量 mm]}"""
    out = {}
    for yr in YEARS:
        p = os.path.join(ROOT, "precip_tif", "precip_%d.tif" % yr)
        with rasterio.open(p) as src:
            w = from_bounds(*STUDY, src.transform).round_offsets().round_lengths()
            data = src.read(window=w).astype(np.float32)     # (12, rows, cols)
            data[data == -32768] = np.nan
        monthly = []
        for b in range(12):
            v = data[b]
            v = v[np.isfinite(v)]
            monthly.append(round(float(np.median(v)) * 0.1, 1) if v.size else 0.0)
        out[yr] = monthly
    return out


def depth_histogram():
    """水深分布直方图(用 100 年最严重场景) + 预警等级"""
    p = os.path.join(ROOT, "flood_out", "flood_depth_100y.tif")
    with rasterio.open(p) as src:
        d = src.read(1).astype("float32")
    d = d[d > 0.05]
    bins = [(0.05, 0.5), (0.5, 1), (1, 2), (2, 3), (3, 5), (5, 1e9)]
    labels = ["0-0.5m", "0.5-1m", "1-2m", "2-3m", "3-5m", ">5m"]
    counts = [int(((d > lo) & (d <= hi)).sum()) for lo, hi in bins]
    # 预警等级: 蓝<0.5 黄0.5-1 橙1-2 红>2
    warn = {
        "蓝": int((d <= 0.5).sum()),
        "黄": int(((d > 0.5) & (d <= 1)).sum()),
        "橙": int(((d > 1) & (d <= 2)).sum()),
        "红": int((d > 2).sum()),
    }
    return {"labels": labels, "counts": counts, "warn": warn}


def main():
    scenes = json.load(open(os.path.join(ROOT, "flood_out", "scenarios.json"), encoding="utf-8"))
    rain = study_monthly_rain()
    hist = depth_histogram()
    payload = {
        "scenarios": scenes,
        "years": YEARS,
        "months": MONTHS,
        "monthly_rain": rain,
        "depth_hist": hist,
    }
    out = os.path.join(ROOT, "dashboard_data.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// auto-generated by export_dashboard.py\nvar DASHBOARD_DATA = "
                + json.dumps(payload, ensure_ascii=False) + ";")
    print("wrote %s" % out)
    print("  月降雨 2021:", rain[2021])
    print("  水深直方图:", hist["labels"], hist["counts"])
    print("  预警等级:", hist["warn"])


if __name__ == "__main__":
    main()
