# -*- coding: utf-8 -*-
"""
export_unet_demo.py — 生成 UNet 水体提取演示样本(供 unet.html 展示):
  对验证集中含水的样本跑推理, 存 原图RGB / 预测掩膜 / 真值掩膜, 并输出 unet_samples.js(含统计)。
"""
import os, glob, random, json
import numpy as np
import tifffile
import torch
from PIL import Image
from unet_model import UNet

DATA = r"D:\Competiton\GF-FloodNet\GF-FloodNet-v1"
CKPT = r"D:\Competiton\unet_out\unet_water.pt"
OUT = r"D:\Competiton\unet_out\samples"


def to_rgb(I):
    rgb = I[:, :, [2, 1, 0]].astype(np.float32)          # R,G,B
    for c in range(3):
        rgb[:, :, c] = (rgb[:, :, c] - rgb[:, :, c].min()) / (rgb[:, :, c].max() - rgb[:, :, c].min() + 1e-6) * 255
    return np.array(rgb, dtype=np.uint8)


def main(n=6):
    os.makedirs(OUT, exist_ok=True)
    ck = torch.load(CKPT, map_location="cpu")
    mean, std, size = ck["mean"], ck["std"], ck["size"]
    model = UNet(5, 1, base=ck["base"]); model.load_state_dict(ck["state_dict"]); model.eval()

    anns = sorted(glob.glob(os.path.join(DATA, "annotations", "*.tif")))
    pairs = [(os.path.join(DATA, "images", os.path.basename(a)), a) for a in anns]
    random.Random(0).shuffle(pairs)
    val = pairs[1500:1800]

    samples = []
    for img, a in val:
        A = tifffile.imread(a)
        if (A < 255).sum() < 400:
            continue
        name = os.path.basename(a).replace(".tif", "")
        I = tifffile.imread(img).astype(np.float32)
        if I.shape[0] != size:
            I = np.stack([np.array(Image.fromarray(I[..., b].astype("uint16"), "I;16").resize((size, size)))
                          for b in range(5)], axis=2).astype(np.float32)
            A = np.array(Image.fromarray(A, "L").resize((size, size)))
        gt = (A < 255).astype(np.uint8)
        X = I.transpose(2, 0, 1)
        for b in range(5):
            X[b] = (X[b] - mean[b]) / std[b]
        with torch.no_grad():
            prob = torch.sigmoid(model(torch.from_numpy(X[None])))[0, 0].numpy()
        pred = (prob > 0.5).astype(np.uint8)

        rgb = to_rgb(I)
        p = rgb.copy(); p[pred > 0] = [0, 140, 255]
        g = rgb.copy(); g[gt > 0] = [0, 255, 140]
        Image.fromarray(rgb).save(os.path.join(OUT, name + "_img.png"))
        Image.fromarray(p).save(os.path.join(OUT, name + "_pred.png"))
        Image.fromarray(g).save(os.path.join(OUT, name + "_gt.png"))

        iou = float((pred & gt).sum() / max((pred | gt).sum(), 1))
        samples.append({"name": name, "water_frac": round(float(gt.mean()), 3),
                        "pred_frac": round(float(pred.mean()), 3), "iou": round(iou, 3)})
        if len(samples) >= n:
            break

    with open(r"D:\Competiton\unet_samples.js", "w", encoding="utf-8") as f:
        f.write("// auto-generated by export_unet_demo.py\nvar UNET_SAMPLES = "
                + json.dumps(samples, ensure_ascii=False) + ";")
    print("生成 %d 个演示样本" % len(samples))
    for s in samples:
        print("  %s  真值水体%.1f%%  预测%.1f%%  IoU=%.3f" % (s["name"], 100*s["water_frac"], 100*s["pred_frac"], s["iou"]))


if __name__ == "__main__":
    main()
