# -*- coding: utf-8 -*-
"""
export_web.py — 生成前端(flood.html)所需数据:
  flood_scenarios.js   : 5 个重现期场景参数 + 研究区范围
  flood_depth_{T}y.png : 水深色带 PNG(蓝阶, 透明=未淹, 深蓝=河道/深水)
  buildings_3d.js      : 每栋建筑的地面高程(采样 DTM)+ 高度 + 轮廓
"""
import os, json
import numpy as np
import rasterio
from PIL import Image

os.environ["PROJ_LIB"] = r"D:\Lib\site-packages\rasterio\proj_data"
os.environ["PROJ_DATA"] = r"D:\Lib\site-packages\rasterio\proj_data"

ROOT = r"D:\Competiton"
SCEN = os.path.join(ROOT, "flood_out", "scenarios.json")
DTM = os.path.join(ROOT, "dem", "study_dtm.tif")
BLD = os.path.join(ROOT, "gz_tower_buildings.geojson")
STUDY = dict(west=113.30, south=23.09, east=113.34, north=23.13)
RETURNS = [2, 5, 10, 50, 100]
DEPTH_CAP = 6.0   # 色带上限(m), 超出(河道)按最深色
DEFAULT_GROUND = 8.0


def colorize(depth):
    h, w = depth.shape
    img = np.zeros((h, w, 4), dtype=np.uint8)
    mask = depth > 0.05
    t = np.clip(depth / DEPTH_CAP, 0.0, 1.0)
    r = (166.0 * (1 - t)).astype("uint8")          # 166 -> 0
    g = (227.0 - 176.0 * t).astype("uint8")        # 227 -> 51
    b = (255.0 - 153.0 * t).astype("uint8")        # 255 -> 102
    img[..., 0], img[..., 1], img[..., 2] = r, g, b
    img[..., 3] = np.where(mask, 200, 0).astype("uint8")
    return img


def exterior_ring(geom):
    if geom["type"] == "Polygon":
        return geom["coordinates"][0]
    if geom["type"] == "MultiPolygon":
        return geom["coordinates"][0][0]
    return None


def main():
    scenes = json.load(open(SCEN, encoding="utf-8"))
    # 1) 场景 JS
    js = ["// auto-generated by export_web.py",
          "var FLOOD_SCENARIOS = " + json.dumps(scenes, ensure_ascii=False) + ";",
          "var STUDY_BOUNDS = " + json.dumps(STUDY) + ";",
          "var DEPTH_CAP = %g;" % DEPTH_CAP]
    with open(os.path.join(ROOT, "flood_scenarios.js"), "w", encoding="utf-8") as f:
        f.write("\n".join(js))
    print("wrote flood_scenarios.js  (%d scenarios)" % len(scenes))

    # 2) 水深色带 PNG
    for T in RETURNS:
        p = os.path.join(ROOT, "flood_out", "flood_depth_%dy.tif" % T)
        with rasterio.open(p) as src:
            depth = src.read(1).astype("float32")
        img = Image.fromarray(colorize(depth), "RGBA")
        out = os.path.join(ROOT, "flood_depth_%dy.png" % T)
        img.save(out)
        print("wrote %s  %dx%d" % (out, img.width, img.height))

    # 3) 建筑 3D(采样 DTM 得地面高程)
    gj = json.load(open(BLD, encoding="utf-8"))
    src = rasterio.open(DTM)
    blds = []
    for f in gj["features"]:
        geom = f.get("geometry")
        if not geom:
            continue
        ring = exterior_ring(geom)
        if not ring:
            continue
        props = f.get("properties") or {}
        h = float(props.get("height") or 0)
        xs = [p[0] for p in ring]
        ys = [p[1] for p in ring]
        cx, cy = sum(xs) / len(xs), sum(ys) / len(ys)
        vals = list(src.sample([(cx, cy)]))
        g = float(vals[0][0]) if (vals and vals[0][0] is not None) else DEFAULT_GROUND
        blds.append({"name": props.get("name", ""), "h": round(h, 1),
                     "g": round(g, 1),
                     "ring": [[round(x, 6), round(y, 6)] for x, y in ring]})
    src.close()
    with open(os.path.join(ROOT, "buildings_3d.js"), "w", encoding="utf-8") as f:
        f.write("// auto-generated by export_web.py\nvar BUILDINGS_3D = "
                + json.dumps(blds, ensure_ascii=False) + ";")
    print("wrote buildings_3d.js  (%d buildings)" % len(blds))

    # 4) 淹没范围多边形(3D 水体渲染用)
    ext = {}
    for T in RETURNS:
        gj = json.load(open(os.path.join(ROOT, "flood_out", "flood_extent_%dy.geojson" % T),
                            encoding="utf-8"))
        rings = [f["geometry"]["coordinates"][0] for f in gj["features"]]
        ext[str(T)] = rings
    with open(os.path.join(ROOT, "flood_extent.js"), "w", encoding="utf-8") as f:
        f.write("// auto-generated by export_web.py\nvar FLOOD_EXTENT = "
                + json.dumps(ext, ensure_ascii=False) + ";")
    print("wrote flood_extent.js  (%s)" % {str(T): len(ext[str(T)]) for T in RETURNS})


if __name__ == "__main__":
    main()
