# -*- coding: utf-8 -*-
"""
load_flood_pg.py — 生成 SQL 把 P0b 结果写入 PostGIS:
  flood_scenarios (每重现期一行)
  flood_extent    (淹没范围矢量, Polygon 4326)
flood_depth 栅格表由 raster2pgsql 单独加载(见 load_flood.sh)。
"""
import os, json
ROOT = os.path.dirname(os.path.abspath(__file__))

OUT = os.path.join(ROOT, "flood_out", "load_flood.sql")
SCEN = os.path.join(ROOT, "flood_out", "scenarios.json")
RETURNS = [2, 5, 10, 50, 100]

DDL_SCEN = """
DROP TABLE IF EXISTS flood_scenarios;
CREATE TABLE flood_scenarios (
  return_period_y int PRIMARY KEY,
  rain_mm double precision,
  runoff_depth_m double precision,
  water_level_m double precision,
  max_depth_m double precision,
  mean_depth_m double precision,
  flooded_area_km2 double precision,
  flooded_cells int,
  river_cells int
);
"""

DDL_EXT = """
DROP TABLE IF EXISTS flood_extent;
CREATE TABLE flood_extent (
  gid serial PRIMARY KEY,
  return_period_y int,
  geom geometry(Polygon, 4326)
);
CREATE INDEX flood_extent_geom_idx ON flood_extent USING gist(geom);
CREATE INDEX flood_extent_t_idx ON flood_extent(return_period_y);
"""


def main():
    scenes = json.load(open(SCEN, encoding="utf-8"))
    lines = ["-- auto-generated by load_flood_pg.py", DDL_SCEN]
    for s in scenes:
        lines.append(
            "INSERT INTO flood_scenarios VALUES (%d, %s, %s, %s, %s, %s, %s, %d, %d);" % (
                s["return_period_y"], s["rain_mm"], s["runoff_depth_m"],
                s["water_level_m"], s["max_depth_m"], s["mean_depth_m"],
                s["flooded_area_km2"], s["flooded_cells"], s["river_cells"]))

    lines.append(DDL_EXT)
    n = 0
    for T in RETURNS:
        gj = json.load(open(os.path.join(ROOT, "flood_out", "flood_extent_%dy.geojson" % T),
                            encoding="utf-8"))
        for f in gj["features"]:
            g = json.dumps(f["geometry"], separators=(",", ":"))
            lines.append(
                "INSERT INTO flood_extent (return_period_y, geom) VALUES (%d, ST_GeomFromGeoJSON('%s'));"
                % (T, g))
            n += 1
    lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s  (scenarios=%d, extent polygons=%d)" % (OUT, len(scenes), n))


if __name__ == "__main__":
    main()
