# -*- coding: utf-8 -*-
"""
export_web.py — 生成前端(flood.html)所需数据(写入 web/data/, 2026-10 工程化整理):
  flood_scenarios.js   : 5 个重现期场景参数 + 研究区范围
  flood_depth_{T}y.png : 水深色带 PNG(蓝阶, 透明=未淹, 深蓝=河道/深水)
  buildings_3d.js      : 每栋建筑的地面高程(采样 DTM)+ 高度 + 轮廓
"""
import os, json
import rasterio
from PIL import Image

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # pipeline/ 子目录: 仓库根入 path(共享模块 pipeline_config/proj_fix/...)
import proj_fix  # noqa: F401  PROJ 冲突修复(须在 import rasterio 之前)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # pipeline/ 子目录 -> 仓库根
SCEN = os.path.join(ROOT, "flood_out", "scenarios.json")
DTM = os.path.join(ROOT, "dem", "study_dtm.tif")
BLD = os.path.join(ROOT, "gz_tower_buildings.geojson")
from pipeline_config import STUDY_BOUNDS as STUDY, RETURNS   # 唯一权威定义
from pipeline_config import DEPTH_CAP          # 色带上限/淹没阈值唯一权威
from flood_render import colorize_depth                       # 色带唯一实现(与 app.py 同源, ARC-01)
DEFAULT_GROUND = 8.0


def exterior_ring(geom):
    if geom["type"] == "Polygon":
        return geom["coordinates"][0]
    if geom["type"] == "MultiPolygon":
        return geom["coordinates"][0][0]
    return None


def main():
    scenes = json.load(open(SCEN, encoding="utf-8"))
    # 1) 场景 JS
    js = ["// auto-generated by export_web.py",
          "var FLOOD_SCENARIOS = " + json.dumps(scenes, ensure_ascii=False) + ";",
          "var STUDY_BOUNDS = " + json.dumps(STUDY) + ";",
          "var DEPTH_CAP = %g;" % DEPTH_CAP]
    with open(os.path.join(ROOT, "web", "data", "flood_scenarios.js"), "w", encoding="utf-8") as f:
        f.write("\n".join(js))
    print("wrote flood_scenarios.js  (%d scenarios)" % len(scenes))

    # 2) 水深色带 PNG
    land = None
    try:
        import rasterio as _rio
        with _rio.open(os.path.join(ROOT, "dem", "study_dtm.tif")) as _s:
            land = _s.read(1).astype("float32") > 0   # 陆域掩膜, 排除常年河道
    except Exception as _e:
        print("  DTM 不可读, PNG 将不含陆域遮膜:", _e)
    for T in RETURNS:
        p = os.path.join(ROOT, "flood_out", "flood_depth_%dy.tif" % T)
        with rasterio.open(p) as src:
            depth = src.read(1).astype("float32")
        img = Image.fromarray(colorize_depth(depth, land=land), "RGBA")
        out = os.path.join(ROOT, "web", "data", "flood_depth_%dy.png" % T)
        img.save(out)
        print("wrote %s  %dx%d" % (out, img.width, img.height))

    # 3) 建筑 3D(采样 DTM 得地面高程)
    gj = json.load(open(BLD, encoding="utf-8"))
    src = rasterio.open(DTM)
    blds = []
    for f in gj["features"]:
        geom = f.get("geometry")
        if not geom:
            continue
        ring = exterior_ring(geom)
        if not ring:
            continue
        props = f.get("properties") or {}
        h = float(props.get("height") or 0)
        xs = [p[0] for p in ring]
        ys = [p[1] for p in ring]
        cx, cy = sum(xs) / len(xs), sum(ys) / len(ys)
        vals = list(src.sample([(cx, cy)]))
        g = float(vals[0][0]) if (vals and vals[0][0] is not None) else DEFAULT_GROUND
        blds.append({"name": props.get("name", ""), "h": round(h, 1),
                     "g": round(g, 1),
                     "ring": [[round(x, 6), round(y, 6)] for x, y in ring]})
    src.close()
    with open(os.path.join(ROOT, "web", "data", "buildings_3d.js"), "w", encoding="utf-8") as f:
        f.write("// auto-generated by export_web.py\nvar BUILDINGS_3D = "
                + json.dumps(blds, ensure_ascii=False) + ";")
    print("wrote buildings_3d.js  (%d buildings)" % len(blds))

    # 4) 淹没范围多边形(3D 水体渲染用)
    ext = {}
    for T in RETURNS:
        gj = json.load(open(os.path.join(ROOT, "flood_out", "flood_extent_%dy.geojson" % T),
                            encoding="utf-8"))
        rings = [f["geometry"]["coordinates"][0] for f in gj["features"]]
        ext[str(T)] = rings
    with open(os.path.join(ROOT, "web", "data", "flood_extent.js"), "w", encoding="utf-8") as f:
        f.write("// auto-generated by export_web.py\nvar FLOOD_EXTENT = "
                + json.dumps(ext, ensure_ascii=False) + ";")
    print("wrote flood_extent.js  (%s)" % {str(T): len(ext[str(T)]) for T in RETURNS})


if __name__ == "__main__":
    main()
