# -*- coding: utf-8 -*-
"""
export_unet_demo.py — 生成 UNet 水体提取演示样本(供 unet.html 展示):
  对验证集中含水的样本跑推理, 存 原图RGB / 预测掩膜 / 真值掩膜, 并输出 unet_samples.js(含统计)。
"""
import os, glob, random, json
import numpy as np
import tifffile
import torch
from PIL import Image
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # pipeline/ 子目录: 仓库根入 path(共享模块 pipeline_config/proj_fix/...)
from unet_model import UNet

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # pipeline/ 子目录 -> 仓库根
DATA = os.path.join(ROOT, "GF-FloodNet", "GF-FloodNet-v1")
CKPT = os.path.join(ROOT, "unet_out", "unet_water.pt")
OUT = os.path.join(ROOT, "unet_out", "samples")


def to_rgb(I):
    rgb = I[:, :, [2, 1, 0]].astype(np.float32)          # R,G,B
    for c in range(3):
        rgb[:, :, c] = (rgb[:, :, c] - rgb[:, :, c].min()) / (rgb[:, :, c].max() - rgb[:, :, c].min() + 1e-6) * 255
    return np.array(rgb, dtype=np.uint8)


def main(n=6):
    os.makedirs(OUT, exist_ok=True)
    ck = torch.load(CKPT, map_location="cpu", weights_only=True)
    mean, std, size = ck["mean"], ck["std"], ck["size"]
    model = UNet(5, 1, base=ck["base"]); model.load_state_dict(ck["state_dict"]); model.eval()

    anns = sorted(glob.glob(os.path.join(DATA, "annotations", "*.tif")))
    pairs = [(os.path.join(DATA, "images", os.path.basename(a)), a) for a in anns]
    # 训练按"场景(region)"划分时, 演示样本必须只取 val_scenes(未参与训练),
    # 否则精度卡混入训练样本会虚高(如场景内插值 IoU≈0.99), 对评审失真。
    val_scenes = set((ck.get("meta") or {}).get("val_scenes") or [])

    def scene_of(path):
        stem = os.path.basename(path).rsplit(".", 1)[0]
        return "_".join(stem.split("_")[:2])

    if val_scenes:
        pairs = [p for p in pairs if scene_of(p[1]) in val_scenes]
        source = "GF-FloodNet 验证集(val_scenes, 未参与训练)"
    else:
        # 旧 ckpt 无场景元数据时的兜底(划分关系不可考, 应重训或补 meta)
        pairs = pairs[1500:1800]
        source = "GF-FloodNet(场景划分关系不可考)"
    random.Random(0).shuffle(pairs)

    samples = []
    for img, a in pairs:
        A = tifffile.imread(a)
        wf = float((A < 255).mean())
        # 过滤退化样本: 几乎无水(微水量 IoU 天然归零, 无信息量)或全水标注(常为标签伪影)
        if wf < 0.03 or wf > 0.95:
            continue
        name = os.path.basename(a).replace(".tif", "")
        I = tifffile.imread(img).astype(np.float32)
        if I.shape[0] != size:
            I = np.stack([np.array(Image.fromarray(I[..., b].astype("uint16"), "I;16").resize((size, size)))
                          for b in range(5)], axis=2).astype(np.float32)
            # 标签是二值分类: 必须 NEAREST, 默认重采样会产生 <255 晕边改变水面占比
            A = np.array(Image.fromarray(A, "L").resize((size, size), Image.NEAREST))
        gt = (A < 255).astype(np.uint8)
        X = I.transpose(2, 0, 1)
        for b in range(5):
            X[b] = (X[b] - mean[b]) / std[b]
        with torch.no_grad():
            prob = torch.sigmoid(model(torch.from_numpy(X[None])))[0, 0].numpy()
        pred = (prob > 0.5).astype(np.uint8)

        rgb = to_rgb(I)
        p = rgb.copy(); p[pred > 0] = [0, 140, 255]
        g = rgb.copy(); g[gt > 0] = [0, 255, 140]
        Image.fromarray(rgb).save(os.path.join(OUT, name + "_img.png"))
        Image.fromarray(p).save(os.path.join(OUT, name + "_pred.png"))
        Image.fromarray(g).save(os.path.join(OUT, name + "_gt.png"))

        iou = float((pred & gt).sum() / max((pred | gt).sum(), 1))
        # 演示样本选择规则(透明): 水面占比 3–95% 且预测非完全失败(IoU≥0.05);
        # 全集口径的验证精度以训练时 val_iou(≈0.60, 场景级划分)为准, 此处仅取可读性样本
        if iou < 0.05:
            continue
        samples.append({"name": name, "water_frac": round(float(gt.mean()), 3),
                        "pred_frac": round(float(pred.mean()), 3), "iou": round(iou, 3)})
        if len(samples) >= n:
            break

    with open(os.path.join(ROOT, "web", "data", "unet_samples.js"), "w", encoding="utf-8") as f:
        f.write("// auto-generated by export_unet_demo.py\n"
                "var UNET_SAMPLES_META = " + json.dumps({"source": source, "val_scenes": sorted(val_scenes)}, ensure_ascii=False) + ";\n"
                "var UNET_SAMPLES = " + json.dumps(samples, ensure_ascii=False) + ";")
    print("样本来源:", source)
    print("生成 %d 个演示样本" % len(samples))
    for s in samples:
        print("  %s  真值水体%.1f%%  预测%.1f%%  IoU=%.3f" % (s["name"], 100*s["water_frac"], 100*s["pred_frac"], s["iou"]))


if __name__ == "__main__":
    main()
